import * as React from "react";
const { useRef, useEffect } = React;
import {
	Component,
	FileSystemAdapter,
	MarkdownRenderer as ObsidianMarkdownRenderer,
	Platform,
	TFile,
} from "obsidian";
import { convertWslPathToWindows } from "../../utils/platform";
import { isAbsolutePath } from "../../utils/paths";
import type AgentClientPlugin from "../../plugin";

interface MarkdownRendererProps {
	text: string;
	plugin: AgentClientPlugin;
}

const PATH_LINK_CLASS = "agent-client-text-path-link";

// Match path-like strings: at least one "/" segment, ending with .ext (1-10 chars).
// Allows word chars, dashes, dots, and CJK characters in segments.
const PATH_PATTERN =
	/(?:[\w\-.\u4e00-\u9fff]+\/)+[\w\-.\u4e00-\u9fff]+\.\w{1,10}/g;

function resolveVaultPath(
	rawPath: string,
	plugin: AgentClientPlugin,
	normalizedVaultBase: string | null,
): string | null {
	const direct = plugin.app.vault.getAbstractFileByPath(rawPath);
	if (direct instanceof TFile) return rawPath;

	if (normalizedVaultBase && rawPath.startsWith(normalizedVaultBase + "/")) {
		const relative = rawPath.slice(normalizedVaultBase.length + 1);
		const file = plugin.app.vault.getAbstractFileByPath(relative);
		if (file instanceof TFile) return relative;
	}
	return null;
}

function linkifyPaths(
	root: HTMLElement,
	plugin: AgentClientPlugin,
	normalizedVaultBase: string | null,
) {
	const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
	const candidates: Text[] = [];
	let node: Node | null;
	while ((node = walker.nextNode())) {
		const parent = (node as Text).parentElement;
		if (!parent) continue;
		// Skip existing links and code blocks (allow inline <code>).
		if (parent.closest(`a, pre, .${PATH_LINK_CLASS}`)) continue;
		const value = node.nodeValue;
		if (!value) continue;
		PATH_PATTERN.lastIndex = 0;
		if (PATH_PATTERN.test(value)) {
			candidates.push(node as Text);
		}
	}

	for (const textNode of candidates) {
		const text = textNode.nodeValue || "";
		const fragment = document.createDocumentFragment();
		let lastIdx = 0;
		let didReplace = false;

		PATH_PATTERN.lastIndex = 0;
		for (const match of text.matchAll(PATH_PATTERN)) {
			const start = match.index ?? 0;
			const matched = match[0];
			const resolved = resolveVaultPath(
				matched,
				plugin,
				normalizedVaultBase,
			);
			if (!resolved) continue;

			if (start > lastIdx) {
				fragment.appendChild(
					document.createTextNode(text.slice(lastIdx, start)),
				);
			}

			const link = document.createElement("a");
			link.className = PATH_LINK_CLASS;
			link.href = "#";
			link.textContent = matched;
			link.dataset.path = resolved;
			link.title = resolved;
			fragment.appendChild(link);

			lastIdx = start + matched.length;
			didReplace = true;
		}

		if (didReplace) {
			if (lastIdx < text.length) {
				fragment.appendChild(
					document.createTextNode(text.slice(lastIdx)),
				);
			}
			textNode.replaceWith(fragment);
		}
	}
}

export function MarkdownRenderer({ text, plugin }: MarkdownRendererProps) {
	const containerRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		const el = containerRef.current;
		if (!el) return;
		el.empty?.();
		el.classList.add("markdown-rendered");

		// Create a temporary component for the markdown renderer lifecycle
		const component = new Component();
		component.load();

		const vaultBasePath =
			plugin.app.vault.adapter instanceof FileSystemAdapter
				? plugin.app.vault.adapter.getBasePath()
				: null;

		const isWslMode = Platform.isWin && plugin.settings.windowsWslMode;
		const normalizedVaultBase = vaultBasePath
			? vaultBasePath.replace(/\\/g, "/").replace(/\/+$/, "")
			: null;

		let cancelled = false;
		void ObsidianMarkdownRenderer.render(
			plugin.app,
			text,
			el,
			"",
			component,
		).then(() => {
			if (cancelled) return;
			linkifyPaths(el, plugin, normalizedVaultBase);
		});

		const handleClick = (e: MouseEvent) => {
			const target = e.target as HTMLElement;

			// Plain-text path links generated by linkifyPaths
			const pathLink = target.closest(
				`a.${PATH_LINK_CLASS}`,
			) as HTMLAnchorElement | null;
			if (pathLink) {
				e.preventDefault();
				const path = pathLink.dataset.path;
				if (path) {
					void plugin.app.workspace.openLinkText(path, "");
				}
				return;
			}

			// Markdown internal links (Obsidian wikilink [[...]] syntax)
			const internalLink = target.closest("a.internal-link");
			if (internalLink) {
				e.preventDefault();
				const rawHref = internalLink.getAttribute("data-href");
				if (rawHref) {
					let href = decodeURIComponent(rawHref);

					if (isWslMode && href.startsWith("/mnt/")) {
						href = convertWslPathToWindows(href);
					}

					const normalizedHref = href.replace(/\\/g, "/");

					if (
						normalizedVaultBase &&
						normalizedHref.startsWith(normalizedVaultBase + "/")
					) {
						const relativePath = normalizedHref.slice(
							normalizedVaultBase.length + 1,
						);
						void plugin.app.workspace.openLinkText(
							relativePath,
							"",
						);
					} else if (!isAbsolutePath(href)) {
						void plugin.app.workspace.openLinkText(href, "");
					}
				}
				return;
			}

			// Standard Markdown links [text](path) that point into the vault.
			// Obsidian's markdown renderer emits these as plain <a> elements
			// *without* the `internal-link` class, so the block above misses
			// them. Agents frequently produce such links (e.g., Codex emits
			// `[Session Log.md](/mnt/c/.../vault/Session Log.md)` on WSL),
			// which would otherwise open an empty tab in Obsidian.
			// See upstream issue RAIT-09/obsidian-agent-client#208.
			const plainLink = target.closest(
				"a:not(.internal-link):not(.external-link)",
			);
			if (plainLink instanceof HTMLAnchorElement) {
				const rawHref =
					plainLink.getAttribute("href") ||
					plainLink.dataset.href ||
					"";
				if (!rawHref || rawHref === "#" || rawHref.startsWith("#")) {
					return;
				}
				// Skip well-known external schemes (http/https/mailto/obsidian/…).
				// File URIs are handled separately below.
				const schemeMatch = rawHref.match(/^([a-zA-Z][a-zA-Z0-9+.-]*):/);
				const scheme = schemeMatch ? schemeMatch[1].toLowerCase() : "";
				if (scheme && scheme !== "file") {
					return;
				}

				let candidate: string;
				try {
					candidate = decodeURIComponent(rawHref);
				} catch {
					candidate = rawHref;
				}

				// Strip `file://` prefix if present (some agents emit URIs).
				if (candidate.toLowerCase().startsWith("file://")) {
					candidate = candidate.replace(/^file:\/\/+/i, "/");
				}

				if (isWslMode && candidate.startsWith("/mnt/")) {
					candidate = convertWslPathToWindows(candidate);
				}

				const normalized = candidate.replace(/\\/g, "/");
				let relativePath: string | null = null;

				if (
					normalizedVaultBase &&
					normalized.startsWith(normalizedVaultBase + "/")
				) {
					relativePath = normalized.slice(
						normalizedVaultBase.length + 1,
					);
				} else if (!isAbsolutePath(candidate) && !scheme) {
					// Relative path — let Obsidian resolve against the vault root.
					relativePath = candidate;
				}

				if (relativePath) {
					// Only intercept if the target actually exists in the vault,
					// otherwise fall through to Obsidian's default behaviour so
					// external-ish links aren't accidentally swallowed.
					const file =
						plugin.app.vault.getAbstractFileByPath(relativePath);
					if (file) {
						e.preventDefault();
						void plugin.app.workspace.openLinkText(
							relativePath,
							"",
						);
					}
				}
			}
		};
		el.addEventListener("click", handleClick);

		return () => {
			cancelled = true;
			el.removeEventListener("click", handleClick);
			component.unload();
		};
	}, [text, plugin]);

	return (
		<div
			ref={containerRef}
			className="agent-client-markdown-text-renderer"
		/>
	);
}
